### ISSUE TITLE
Feedback on the `python INSTALL.py` script

### ISSUE THREAD

**Issue by gdvallance** [spiritumduo/spiritumDuo#27]
### How I ran the script Attempt 1
- I ran the script on a machine with just the dependencies and some containers running ....
- I just hit `return` to use the defaults to see what happened ...

### Comments Attempt 1
1. While it might be obvious to almost all, instructions on how to use the install script should be in instructions.
2. The script says for many instructions that a random string will be generated. Where can you get the results? Having random strings being generated is good, but you need to know where they are ... (I found them, but instructions to say you can get them from the `.env` file would be good
3. Where there is no default (for the email address) I would add say: (no default, please enter a valid email address)

## Result Attempt 1
- Overall a **FAIL** and the script said that the installation was successful!
- **None** of the `docker` containers built.
- There was an exception in migrating the database schema step #8
- Useful error? "The command 'bin/sh c yarn install --development --silent' returned a non-zero code 1 ERROR: Service 'sd-frontend' failed to build : build failed"
- I suspect it is because there were conflicts with other containers ... Trying again after deleting all running containers and images on the machine ...
- It is a **BAD** thing for a script to say there was a successful installation when evidentially it hadn't. Some post checking?

## Attempt 2
- I ran the script on a machine with just the dependencies ...
- I just hit `return` to use the defaults to see what happened ...

### Comments Attempt 2
1. In the `prod` build of the script I would parse the email entry and ensure only a valid email address was supplied

## Result Attempt 2
- The over-writing of an existing `.env` file does not work AND saying "no" does not work either! (at base)
- The over-writing of the other `.env` files in the other locations doesn't work either, but you can successfully say "No" this time.
- Overall a **FAIL** and the script said that the installation was successful!
- **None** of the `docker` containers built.
- Similar errors as before.
- I wonder if some of the issues are due to being on my Trust VPN ...

### How I ran the script Attempt 3
- I ran the script on a machine with just the dependencies and some containers running ....
- I just hit `return` to use the defaults to see what happened ...

### Comments Attempt 3
- On step #6: Get a warning 4/5 run install that there is non-deterministic behaviour so skipping with respect to npm@apollo-client-*
- Then *lots* of warnings which I did not get before which is suggestive ...
- It is clear that in some environments the `yarn` port is blocked which prevents a successful build ...

## Result Attempt 3
- This time a successful build of all the containers **BUT** Steps had errors/tracebacks: 8 (concerning `sd-postgres` password authentication failing), 10 (a consequence of 8?)
- Still says the installation was successful.
- So better but still a **FAIL** ...

**Comment by gdvallance** [comment]
After our discussion and testing it looks like the script works. I have not been able to test properly because the VM on my machine is not-working so-well presently.

**Comment by jcf54** [comment]
Thanks for testing this, I've been working on it late this evening and hope to get what we've discussed ironed out before we meet Monday.

I've added checks to each command to ensure that they return the correct exit codes, that seems to have fixed the issue where it says it's successful when it's not. I've also clarified the file override confirmation, and added a prompt to enter an email address where appropriate (images below).

![image](https://user-images.githubusercontent.com/47789741/162546914-13dead9a-a6b2-48c9-8366-6eb6df1acdc9.png)

![image](https://user-images.githubusercontent.com/47789741/162546767-aa29e6d6-e4c2-44b0-81dc-4f356fbecd85.png)

Addressing our issue earlier where the postgres credentials were incorrect because the container was built previously, I hope to give the user a prompt to remove the volume if it's already present to avoid issues like these. 

I haven't found anything solid re your connection issues using your trust's VPN, though I'll play around with adding latency to see if I can reproduce the issue on my end.

Regarding your point around email validation for SSL certificates, I'll split the install script into production and development, wherein development will skip the email prompt all together as it's not necessary in the development environment

**Comment by jcf54** [comment]
I've just pushed changes to both `INSTALL.md` and `INSTALL.py` (now `INSTALL.dev.py`) that implement what we've discussed above. I haven't been able to repro your issue using your trust's VPN though, I'll have to do some more digging into that.

**Comment by gdvallance** [comment]
Further to the above comment, running through the script again a few points to note: 

1. The rebuild using this script doing it a *second* time is far more efficient than all previous builds due to not rebuilding the yarn elements again.
2. The exception I got first time around did NOT reoccur.
3. Only noticeable error was at step 10 with: ERROR [alembic.runtime.migration] Target database is not up to date. FAILED: Target database is not up to date. Database already exists. This does not appear to matter ...
4. This time we have all the data it appears.

So as far as a go through and not try and break anything run -- it appears to be good-to-go.

**Comment by jcf54** [comment]
I've pushed a couple fixes that should solve the issues you've encountered here. I've run it on a fresh install and existing install and it's all playing nice #worksonmymachine
